#undef spi_master_init
#undef spi_master
#undef spi_pin_init
#undef spi_master_send_byte_sync
#undef spi_master_send_bytes_async_circular
#undef spi_enable
#undef spi_disable
#undef SPI_IRQHandler
#undef spi_complete_callback_circular
#undef spi_early_init
#undef spi_reset_dma
#undef spi_busy
#undef spi_init
#undef SPIBASE
#undef SPI_IRQ
#undef r_CORTEX_M_SPI_DR
#undef r_CORTEX_M_SPI_CR1
#undef r_CORTEX_M_SPI_CR2
#undef r_CORTEX_M_SPI_SR
#undef spi_dmastatus
#undef spiname
#undef spi_power_up
#undef spi_enabling_irqs
#undef spi_configuration
#undef spi_role
#undef spi_baudrate
#undef spi_cpol
#undef spi_cpha
#undef spi_frame
#undef spi_lsb
#undef spi_TI_mode
#undef spi_dma
#undef spi_dmadesc
#undef spi_dev_infos
#undef CONFIG_SPI_ROLE_MASTER
#undef spi_set_baudrate
#undef spi_get_baudrate
#undef spi_set_endianness
#undef spi_set_frame
#undef spi_set_cpol_cpha
